// import 'package:dei_champions/widgets/others/app_bar_common.dart';
// import 'package:flutter/material.dart';
//
// import '../../../models/job/job_model.dart';
// import '../job/components/similar_jobs.dart';
//
//
//
// class SimilarJobsListScreen extends StatelessWidget {
//   const SimilarJobsListScreen({super.key});
//
//   static final List<JobModel> jobs = [
//     JobModel(
//       title: "45days WFH Malayalam, Telugu",
//       companyName: "Teleperformance (TP)",
//       location: "Remote",
//       experience: "0-1 yrs",
//       salary: "50,000 - 1.5 Lacs PA",
//       skills: ["Telugu", "Malayalam", "Voice Process", "Voice", "Process"],
//       vacancies: "10 vacancies",
//       postedTime: "5d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/briefcase.png",
//       hasAwards: true,
//       hasReviews: false,
//       hasBenefits: true,
//       hasVerifiedBenefits: false,
//       hasSalaryInsights: true,
//       rating: 4.2,
//     ),
//     JobModel(
//       title: "WFH - Data Entry",
//       companyName: "Creative Hands HR",
//       location: "Hybrid - Chennai, Coimbatore, Bengaluru",
//       experience: "0-5 yrs",
//       salary: "2 - 4.5 Lacs PA",
//       skills: ["Typing", "Back office", "Computer Operating", "Data Entry"],
//       vacancies: "Multiple",
//       postedTime: "4d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/shopping-cart.png",
//       hasAwards: false,
//       hasReviews: true,
//       hasBenefits: false,
//       hasVerifiedBenefits: false,
//       hasSalaryInsights: true,
//       rating: 3.8,
//     ),
//     JobModel(
//       title: "Pharmacist",
//       companyName: "Narayana Hrudayalaya Pvt Ltd",
//       location: "Bengaluru",
//       experience: "0-3 yrs",
//       salary: "Not disclosed",
//       skills: ["Pharmacist", "Healthcare", "Medicine"],
//       vacancies: "Not specified",
//       postedTime: "2d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/hospital-room.png",
//       hasAwards: true,
//       hasReviews: true,
//       hasBenefits: false,
//       hasVerifiedBenefits: true,
//       hasSalaryInsights: false,
//       rating: 4.5,
//     ),
//     JobModel(
//       title: "Flutter Developer",
//       companyName: "Infosys",
//       location: "Coimbatore",
//       experience: "1-3 yrs",
//       salary: "2 - 3 Lacs PA",
//       skills: ["Flutter", "Dart", "Provider", "Firebase"],
//       vacancies: "3 vacancies",
//       postedTime: "28d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/google-logo.png",
//       hasAwards: false,
//       hasReviews: true,
//       hasBenefits: true,
//       hasVerifiedBenefits: false,
//       hasSalaryInsights: true,
//       rating: 4.0,
//     ),
//     JobModel(
//       title: "Java Backend Developer",
//       companyName: "TCS",
//       location: "Bengaluru",
//       experience: "2-5 yrs",
//       salary: "4 - 6 Lacs PA",
//       skills: ["Java", "Spring Boot", "Microservices", "MySQL"],
//       vacancies: "5 vacancies",
//       postedTime: "10d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/microsoft.png",
//       hasAwards: true,
//       hasReviews: false,
//       hasBenefits: true,
//       hasVerifiedBenefits: true,
//       hasSalaryInsights: false,
//       rating: 4.3,
//     ),
//     JobModel(
//       title: "Software Engineer - Node.js",
//       companyName: "Wipro",
//       location: "Hyderabad",
//       experience: "1-4 yrs",
//       salary: "3 - 5 Lacs PA",
//       skills: ["Node.js", "Express", "MongoDB", "REST API"],
//       vacancies: "2 vacancies",
//       postedTime: "7d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/ibm.png",
//       hasAwards: false,
//       hasReviews: true,
//       hasBenefits: true,
//       hasVerifiedBenefits: false,
//       hasSalaryInsights: true,
//       rating: 3.9,
//     ),
//     JobModel(
//       title: "React Native Developer",
//       companyName: "HCL",
//       location: "Chennai",
//       experience: "0-2 yrs",
//       salary: "2 - 4 Lacs PA",
//       skills: ["React Native", "JavaScript", "Redux", "API Integration"],
//       vacancies: "4 vacancies",
//       postedTime: "3d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/briefcase.png",
//       hasAwards: true,
//       hasReviews: true,
//       hasBenefits: false,
//       hasVerifiedBenefits: true,
//       hasSalaryInsights: false,
//       rating: 4.4,
//     ),
//     JobModel(
//       title: "Customer Support Executive",
//       companyName: "Concentrix",
//       location: "Remote",
//       experience: "0-1 yrs",
//       salary: "1.2 - 2 Lacs PA",
//       skills: ["English", "Customer Service", "Communication"],
//       vacancies: "15 vacancies",
//       postedTime: "1d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/shopping-cart.png",
//       hasAwards: false,
//       hasReviews: true,
//       hasBenefits: true,
//       hasVerifiedBenefits: false,
//       hasSalaryInsights: true,
//       rating: 3.7,
//     ),
//     JobModel(
//       title: "Data Analyst",
//       companyName: "Cognizant",
//       location: "Pune",
//       experience: "1-3 yrs",
//       salary: "3 - 4.5 Lacs PA",
//       skills: ["SQL", "Excel", "Python", "PowerBI"],
//       vacancies: "2 vacancies",
//       postedTime: "6d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/amazon.png",
//       hasAwards: true,
//       hasReviews: false,
//       hasBenefits: true,
//       hasVerifiedBenefits: true,
//       hasSalaryInsights: true,
//       rating: 4.1,
//     ),
//     JobModel(
//       title: "Android Developer",
//       companyName: "Tech Mahindra",
//       location: "Mumbai",
//       experience: "1-4 yrs",
//       salary: "3 - 5 Lacs PA",
//       skills: ["Java", "Kotlin", "Android Studio", "Firebase"],
//       vacancies: "3 vacancies",
//       postedTime: "8d ago",
//       logoUrl: "https://img.icons8.com/color/96/000000/meta.png",
//       hasAwards: false,
//       hasReviews: true,
//       hasBenefits: false,
//       hasVerifiedBenefits: true,
//       hasSalaryInsights: true,
//       rating: 3.6,
//     ),
//   ];
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: appBarCommon(title:"371 Similar jobs" ),
//       body: SafeArea(
//         child: SingleChildScrollView(
//           padding: EdgeInsets.symmetric(horizontal: 16,vertical: 16),
//           child: SimilarJobsListView(jobs: jobs),
//         ),
//       ),
//     );
//   }
// }
