// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get ncurrentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPslTnqzzyvyFG499QNGWDI_KbgVMX5o',
    appId: '1:325714813742:android:70baa600d4c1d1e7be90bf',
    messagingSenderId: '325714813742',
    projectId: 'dei-champions',
    storageBucket: 'dei-champions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUuS-xHgIlaKKNjwGFRxDitDk4Rv_dc4g',
    appId: '1:325714813742:ios:07eadc00fb4e6e9bbe90bf',
    messagingSenderId: '325714813742',
    projectId: 'dei-champions',
    storageBucket: 'dei-champions.firebasestorage.app',
    androidClientId: '325714813742-a6qudjd6mjqavjcsv9b7abrull1n9kj1.apps.googleusercontent.com',
    iosClientId: '325714813742-me68iclfkd366hg8b378pv6fspt2eqtf.apps.googleusercontent.com',
    iosBundleId: 'com.drmstc.deiChampions',
  );

}